//! Subframe gain dequantisation (RFC 6716 §4.2.7.4; normative
//! `gain_quant.c`), uniform on a log scale.
//!
//! The decoded gain indices accumulate into `prev_ind` (delta coding with a
//! double-step extension above a threshold), clamp to the 64 quantisation
//! levels, and convert to linear Q16 via [`log2lin`](super::math::log2lin).

#![allow(dead_code, reason = "consumed incrementally as the SILK decoder stages land")]

use super::indices::MAX_NB_SUBFR;
use super::math::{log2lin, smulwb};

/// `N_LEVELS_QGAIN`.
const N_LEVELS_QGAIN: i32 = 64;
/// `MAX_DELTA_GAIN_QUANT` / `MIN_DELTA_GAIN_QUANT`.
const MAX_DELTA_GAIN_QUANT: i32 = 36;
const MIN_DELTA_GAIN_QUANT: i32 = -4;
/// `OFFSET` (gain_quant.c): `(MIN_QGAIN_DB * 128) / 6 + 16 * 128`.
const OFFSET: i32 = (2 * 128) / 6 + 16 * 128;
/// `INV_SCALE_Q16`: `(65536 * ((MAX-MIN)_DB * 128 / 6)) / (N_LEVELS - 1)`.
const INV_SCALE_Q16: i32 = (65536 * (((88 - 2) * 128) / 6)) / (N_LEVELS_QGAIN - 1);

/// `silk_gains_dequant`: per-subframe linear Q16 gains from the decoded
/// indices; `prev_ind` is the cross-frame accumulator (`LastGainIndex`).
pub(crate) fn gains_dequant(
    ind: &[i8; MAX_NB_SUBFR],
    prev_ind: &mut i8,
    conditional: bool,
    nb_subfr: usize,
) -> [i32; MAX_NB_SUBFR] {
    let mut gain_q16 = [0i32; MAX_NB_SUBFR];
    for k in 0..nb_subfr {
        if k == 0 && !conditional {
            // The index may not drop more than 16 steps (~21.8 dB).
            *prev_ind = i32::from(ind[k]).max(i32::from(*prev_ind) - 16) as i8;
        } else {
            let ind_tmp = i32::from(ind[k]) + MIN_DELTA_GAIN_QUANT;
            // Accumulate deltas, with double steps above the threshold.
            let double_step_size_threshold = 2 * MAX_DELTA_GAIN_QUANT - N_LEVELS_QGAIN + i32::from(*prev_ind);
            if ind_tmp > double_step_size_threshold {
                *prev_ind = (i32::from(*prev_ind) + ((ind_tmp << 1) - double_step_size_threshold)) as i8;
            } else {
                *prev_ind = (i32::from(*prev_ind) + ind_tmp) as i8;
            }
        }
        *prev_ind = i32::from(*prev_ind).clamp(0, N_LEVELS_QGAIN - 1) as i8;

        // Scale and convert to linear (3967 = 31 in Q7).
        gain_q16[k] = log2lin((smulwb(INV_SCALE_Q16, i32::from(*prev_ind)) + OFFSET).min(3967));
    }
    gain_q16
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Pins generated by compiling the reference `gain_quant.c` and calling
    /// `silk_gains_dequant` with these exact sequences.
    #[test]
    fn dequant_matches_reference_pins() {
        // Independent first frame: indices [32, 20, 20, 25], prev starts 10.
        let mut prev = 10i8;
        let gains = gains_dequant(&[32, 20, 20, 25], &mut prev, false, 4);
        assert_eq!(gains, [12_713_984, 158_334_976, 1_686_110_208, 1_686_110_208]);
        assert_eq!(prev, 63);

        // Conditional follow-up frame: deltas [4, 0, 5, 8].
        let gains = gains_dequant(&[4, 0, 5, 8], &mut prev, true, 4);
        assert_eq!(gains, [1_686_110_208, 897_581_056, 1_048_576_000, 1_686_110_208]);
        assert_eq!(prev, 63);

        // Independent restart from a low accumulator.
        let mut prev = 0i8;
        let gains = gains_dequant(&[40, 0, 0, 0], &mut prev, false, 4);
        assert_eq!(gains, [44_826_624, 23_855_104, 12_713_984, 6_782_976]);
        assert_eq!(prev, 28);
    }
}
