//! Differential loss check against a libopus reference decode
//! (`/tmp/loss_ref*.f32`, generated by the C harness in the dev notes).
use ruopus::{OpusDecoder, Packet};

fn main() {
    let vector = std::env::args().nth(1).unwrap_or_else(|| "testvector02".into());
    let refpath = std::env::args().nth(2).expect("usage: loss_check <vector> <ref.f32>");
    let data = std::fs::read(format!("tests/vectors/{vector}.bit")).unwrap();
    let mut packets = Vec::new();
    let mut off = 0usize;
    while off + 8 <= data.len() {
        let len = u32::from_be_bytes(data[off..off + 4].try_into().unwrap()) as usize;
        off += 8;
        packets.push(&data[off..off + len]);
        off += len;
    }
    let mut dec = OpusDecoder::new(2);
    let mut pcm: Vec<f32> = Vec::new();
    for (idx, pkt) in packets.iter().enumerate() {
        if idx % 10 == 7 {
            let parsed = Packet::parse(pkt).unwrap();
            let dur = parsed.frames().len() * parsed.toc().frame_size().samples_per_channel_48k();
            pcm.extend(dec.decode_lost(dur));
        } else {
            pcm.extend(dec.decode_packet(pkt).unwrap());
        }
    }
    let refbytes = std::fs::read(&refpath).unwrap();
    let refpcm: Vec<f32> = refbytes
        .chunks_exact(4)
        .map(|c| f32::from_le_bytes(c.try_into().unwrap()))
        .collect();
    println!("ours {} ref {}", pcm.len(), refpcm.len());
    let n = pcm.len().min(refpcm.len());
    let (mut sig, mut noise) = (0.0f64, 0.0f64);
    for j in 0..n {
        sig += f64::from(refpcm[j]) * f64::from(refpcm[j]);
        noise += f64::from(pcm[j] - refpcm[j]) * f64::from(pcm[j] - refpcm[j]);
    }
    println!(
        "SNR vs libopus with 10% loss: {:.1} dB",
        10.0 * (sig / noise.max(1e-30)).log10()
    );
    // First sample index where the streams differ by more than 1e-4.
    if let Some(first) = (0..n).find(|&j| (pcm[j] - refpcm[j]).abs() > 1e-4) {
        println!("first divergence at interleaved sample {first}");
        // Which packet?
        let mut pos = 0usize;
        for (idx, pkt) in packets.iter().enumerate() {
            let parsed = Packet::parse(pkt).unwrap();
            let dur = parsed.frames().len() * parsed.toc().frame_size().samples_per_channel_48k();
            if (pos + dur) * 2 > first {
                println!("  in packet {idx} (lost: {})", idx % 10 == 7);
                break;
            }
            pos += dur;
        }
    }
}
